#!/usr/bin/env python3
"""Verify the taskboard-dev T0 orchestration contract."""

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]


def read_text(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def require_contains(path: str, needle: str) -> None:
    text = read_text(path)
    if needle not in text:
        raise AssertionError(f"{path} is missing required text: {needle}")


def require_not_contains(path: str, needle: str) -> None:
    text = read_text(path)
    if needle in text:
        raise AssertionError(f"{path} contains forbidden text: {needle}")


def verify_t0_contract() -> None:
    require_contains("SKILL.md", "/taskboard-dev T0    # User-facing Orchestrator")
    require_contains("SKILL.md", 'python scripts/taskboard_start.py --goal "<user goal>"')
    require_contains("SKILL.md", "--dry-run --iterations 1 --launcher none")
    require_not_contains("SKILL.md", 'python scripts/taskboard_start.py --goal "<user goal>" --auto')
    require_contains("references/role-t0.md", "## Role: T0 — User-Facing Orchestrator")
    require_contains("references/role-t0.md", "### T0 Operating Loop")
    require_contains("references/role-t0.md", "T0 is manager-only")
    require_contains("references/role-t0.md", "must not directly execute development tasks")
    require_contains("references/role-t0.md", "### T0 Terminal Launcher")
    require_contains("references/role-t0.md", "--launcher windows-terminal")
    require_contains("references/role-t0.md", "--agent-template")
    require_contains("references/role-t0.md", 'claude "{target}"')
    require_contains("references/role-t0.md", "launch-probe")
    require_contains("references/role-t0.md", "recommended_backend")
    require_contains("references/role-t0.md", "launch_probe_recommended_backend")
    require_contains("references/role-t0.md", "taskboard-subagent-backend")
    require_contains("references/role-t0.md", "subagent_prompts")
    require_contains("references/role-t0.md", "taskboard_subagent_acceptance.py --root . --require-real-agent-ids --require-spawn-evidence")
    require_contains("references/role-t0.md", "not live native-subagent execution")
    require_contains("references/role-t0.md", "taskboard_live_milestone_acceptance.py --root .")
    require_contains("references/role-t0.md", "smoke/demo runs are not enough")
    require_contains("references/role-t0.md", "taskboard_t0_boundary_smoke.py")
    require_contains("references/role-t0.md", "T0 dry-start creates PROJECT/MAP/REQUIREMENTS/STATE")
    require_contains("references/role-t0.md", "session_manifest")
    require_contains("references/role-t0.md", "not a new shared state database")
    require_contains("references/role-t0.md", "auto-terminal mode")
    require_contains("references/role-t0.md", "separate terminal session and isolated agent context")
    require_contains("references/role-t0.md", "must not reuse one role's conversation context")
    require_contains("references/role-t0.md", "### Multi-Agent Synchronization")
    require_contains("references/role-t0.md", "Use blackboard synchronization, not chat-context synchronization")
    require_contains("references/role-t0.md", "### T0 Scheduling Logic")
    require_contains("references/role-t0.md", "T0 schedules by event priority, not by arbitrary rotation")
    require_contains("SKILL.md", "### Multi-Agent Patterns Adopted")
    require_contains("SKILL.md", "**Manager/Worker**")
    require_contains("SKILL.md", "**Blackboard**")
    require_contains("SKILL.md", "**Independent Critic**")
    require_contains("SKILL.md", "**Liveness / Heartbeat**")
    require_contains("SKILL.md", "**Stop-Gate Aggregation**")
    require_contains("references/role-t0.md", "### T0 Liveness / Heartbeat Rules")
    require_contains("references/role-t0.md", "**T0 MUST NOT**")
    require_contains("references/role-t0.md", "it does not add `T0-*` task statuses")
    require_contains("references/role-t0.md", "T0 input boundary")
    require_contains("references/role-t0.md", "not T0-authored requirements")
    require_contains("references/role-t0.md", "forbidden seed patterns")
    require_contains("references/role-t0.md", "REQ counts")
    require_contains("references/role-t0.md", "priority labels")
    require_contains("references/role-t0.md", "interface signatures")
    require_contains("references/role-t0.md", "MAP risk sections")
    require_contains("references/role-t0.md", "Startup skill gate")
    require_contains("references/role-t0.md", "Evidence enforcement gate")
    require_contains("references/role-t0.md", "Idle recheck contract")
    require_contains("references/role-t0.md", "do not terminate just because this role queue is empty")
    require_contains("SKILL.md", "first run the cheap role-cycle/liveness command")
    require_contains("SKILL.md", "do not skip liveness refreshes")
    require_contains("SKILL.md", "idle-but-running worker as dead")
    require_not_contains("SKILL.md", "no tool calls, no context re-reads")
    require_contains("tests/pressure/README.md", "`T0-seeding.md`")
    require_contains("tests/pressure/README.md", "`worker-loop.md`")
    require_contains("tests/pressure/README.md", "`managed-launch.md`")
    require_contains("tests/pressure/README.md", "`shared-checkout-collision.md`")
    require_contains("tests/pressure/T0-seeding.md", "LeLamp field run 2026-06-10")
    require_contains("tests/pressure/worker-loop.md", "must not skip liveness refreshes")
    require_contains("tests/pressure/managed-launch.md", "spawn availability is session-environment-specific")
    require_contains("tests/pressure/shared-checkout-collision.md", "same repository index")
    require_contains("references/role-t2.md", "### Evidence Enforcement Gate")
    require_contains("references/role-t2.md", "Missing Required skills evidence is a review failure")
    require_contains("SKILL.md", "**T0 next** (priority order):")
    require_contains(
        "SKILL.md",
        "All tasks archived and goal satisfied → \"T0 complete\"",
    )
    require_not_contains("SKILL.md", "| `T0-")

    require_contains("USER-MANUAL.md", "# taskboard-dev v4.5.25 用户手册")
    require_contains("USER-MANUAL.md", "## 5. T0 编排器操作手册")
    require_contains("USER-MANUAL.md", "## Multi-agent 借鉴原则")
    require_contains("USER-MANUAL.md", "T0 是 manager，不是 worker")
    require_contains("USER-MANUAL.md", "T0 是管理员，不是开发执行者")
    require_contains("USER-MANUAL.md", "T0 不直接执行开发任务")
    require_contains("USER-MANUAL.md", "### T0 启动器脚本")
    require_contains("USER-MANUAL.md", "Windows Terminal")
    require_contains("USER-MANUAL.md", "tmux")
    require_contains("USER-MANUAL.md", "session_manifest")
    require_contains("USER-MANUAL.md", "不是新的共享状态数据库")
    require_contains("USER-MANUAL.md", "auto-terminal 模式")
    require_contains("USER-MANUAL.md", "角色之间不共享聊天上下文")
    require_contains("USER-MANUAL.md", "### 多 agent 信息同步机制")
    require_contains("USER-MANUAL.md", "blackboard synchronization")
    require_contains("USER-MANUAL.md", "不是聊天上下文同步")
    require_contains("USER-MANUAL.md", "T0 的调度逻辑是")
    require_contains("USER-MANUAL.md", "交付闭环优先")
    require_contains("USER-MANUAL.md", "修复优先于新执行")
    require_contains("USER-MANUAL.md", "### 与常见 multi-agent 调度方法对比")
    require_contains("USER-MANUAL.md", "中心调度器 / Manager-Worker")
    require_contains("USER-MANUAL.md", "Swarm / Peer-to-Peer")
    require_contains("USER-MANUAL.md", "### 是否适合用户程序开发")
    require_contains("USER-MANUAL.md", "推荐采用分层策略")
    require_contains("USER-MANUAL.md", "完整 T0 auto-terminal")
    require_contains("USER-MANUAL.md", "T0 不新增 `T0-*` 任务状态")
    require_contains("USER-MANUAL.md", "| T0 | `T1-待决策`")
    require_not_contains("USER-MANUAL.md", "| `T0-")

    require_contains("README.md", "当前版本：**v4.5.25**")
    require_contains("README.md", "T0 用户入口")
    require_contains("README.md", "执行：/taskboard-dev T0")
    require_contains("README.md", "用户默认只需要手动打开 1 个入口终端")
    require_contains("README.md", "自动创建或恢复 `taskboard-T1`")
    require_contains("README.md", "不需要手动开 4 个终端")
    require_contains("README.md", "T0 只做管理员和调度器")
    require_contains("README.md", "不直接执行开发任务")
    require_contains("README.md", "--launcher windows-terminal")
    require_contains("README.md", "python scripts/taskboard_t0.py --goal")
    require_contains("README.md", "python scripts/taskboard_demo.py --root .taskboard-demo --with-heartbeats")
    require_contains("README.md", "python scripts/taskboard_loop.py --root . --goal")
    require_contains("README.md", "--assignment-lease-seconds 300")
    require_contains("README.md", "**Goal Complete**: yes")
    require_contains("README.md", "--no-stop-on-complete")
    require_contains("README.md", "python scripts/taskboard_health.py --root . --stale-minutes 30")
    require_contains("README.md", "python scripts/taskboard_sessions.py --root . probe --stale-seconds 300")
    require_contains("README.md", "--assignment-id T2:TASK-003.v1.T2-review.md")
    require_contains("README.md", "Role runtime contract")
    require_contains("README.md", "assigned_role")
    require_contains("README.md", "managed_by: T0")
    require_contains("README.md", "do not rely on another role's chat context")
    require_contains("README.md", "agent-template references {target_file}")
    require_contains("README.md", "enable target files")
    require_contains("README.md", "use `--launcher none` for no-write dry checks")
    require_contains("README.md", "python scripts/taskboard_next.py --role T0 --root .")

    require_contains("references/taskboard-template.md", "# TASKBOARD v4.5.25 Templates")
    require_contains("references/taskboard-template.md", "## Current T0 Control-Plane Entries")
    require_contains("references/taskboard-template.md", "python scripts/taskboard.py --root . status")
    require_contains("references/taskboard-template.md", "python scripts/taskboard.py --root . launch-probe")
    require_contains("references/taskboard-template.md", "recommended_backend")
    require_contains("references/taskboard-template.md", "python scripts/taskboard.py --root . move")
    require_contains("references/taskboard-template.md", "python scripts/taskboard_start.py --goal")
    require_contains("references/taskboard-template.md", "--dry-run --iterations 1 --launcher none")
    require_contains("references/taskboard-template.md", "Current v4.4 recovery rules")
    require_not_contains("references/taskboard-template.md", 'python scripts/taskboard_start.py --goal "<user goal>" --auto')
    require_not_contains("references/taskboard-template.md", "taskboard_start.py --auto is the one-command T0 entry")
    require_contains("references/taskboard-template.md", "python scripts/taskboard_progress.py --root .")
    require_contains("references/taskboard-template.md", "python scripts/taskboard_watchdog.py --root . --execute")
    require_contains("references/taskboard-template.md", "taskboard-t0-watchdog")
    require_contains("references/taskboard-template.md", ".taskboard/t0/latest.json")
    require_contains("references/taskboard-template.md", ".taskboard/t0/events.jsonl")
    require_contains("references/taskboard-template.md", "Assignment lease expiry")
    require_contains("references/taskboard-template.md", "目标(T0):")
    require_contains("references/taskboard-template.md", "执行: /taskboard-dev T0")

    require_contains("scripts/package.sh", 'VERSION="${VERSION:-v4.5.25}"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard.py"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_start.py"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_t0.py"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_loop.py"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_demo.py"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_e2e_smoke.py"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_cold_resume_smoke.py"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_cold_resume_acceptance.py"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_framework_readiness.py"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_overnight_field_run.py"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_t0_boundary_smoke.py"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_subagent_smoke.py"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_subagent_acceptance.py"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_live_milestone_acceptance.py"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_completion.py"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_progress.py"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_watchdog.py"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_decide.py"')
    require_contains("scripts/taskboard_completion.py", "taskboard-t0-completion-audit")
    require_contains("scripts/taskboard_completion.py", "T0 completion audit is read-only")
    require_contains("scripts/taskboard_completion.py", "must not execute T1/T2/T3 work")
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_stopgates.py"')
    require_contains("scripts/taskboard_stopgates.py", "taskboard-t0-stop-gates")
    require_contains("scripts/taskboard_stopgates.py", "T0 aggregates stop gates")
    require_contains("scripts/taskboard_stopgates.py", "do not ask the user to manage T1/T2/T3")
    require_contains("scripts/taskboard_decide.py", "taskboard-t0-decision")
    require_contains("scripts/taskboard_decide.py", "T0 records user decisions only")
    require_contains("scripts/taskboard_decide.py", "T1-方案需修改")
    require_contains("scripts/taskboard.py", "taskboard-status")
    require_contains("scripts/taskboard.py", "taskboard-next")
    require_contains("scripts/taskboard.py", "taskboard-move")
    require_contains("scripts/taskboard.py", "move_target_path")
    require_contains("scripts/taskboard.py", "archive-")
    require_contains("scripts/taskboard.py", "taskboard-alive")
    require_contains("scripts/taskboard.py", "taskboard-worker-cycle")
    require_contains("scripts/taskboard.py", "taskboard-launch-probe")
    require_contains("scripts/taskboard.py", "recommended_backend")
    require_contains("scripts/taskboard.py", "idle-recheck")
    require_contains("scripts/taskboard.py", "taskboard-stall")
    require_contains("scripts/taskboard.py", "record_decision")
    require_contains("scripts/taskboard.py", "invalid status")
    require_contains("scripts/taskboard.py", "append_history")
    require_contains("scripts/taskboard_demo.py", "dry-run demo")
    require_contains("scripts/taskboard_demo.py", "--with-heartbeats")
    require_contains("scripts/taskboard_demo.py", "pass --force or choose an empty demo root")
    require_contains("scripts/taskboard_e2e_smoke.py", "taskboard-e2e-smoke")
    require_contains("scripts/taskboard_e2e_smoke.py", "T0 did not observe worker acknowledgement")
    require_contains("scripts/taskboard_e2e_smoke.py", "T0 completion audit did not become complete-ready")
    require_contains("scripts/taskboard_e2e_smoke.py", "Completion audit reached complete-ready")
    require_contains("scripts/taskboard_cold_resume_smoke.py", "taskboard-cold-resume-smoke")
    require_contains("scripts/taskboard_cold_resume_smoke.py", "T0 selected T3 from active TASKBOARD state")
    require_contains("scripts/taskboard_cold_resume_smoke.py", "Scoped git status exposes yesterday's partial work")
    require_contains("scripts/taskboard_cold_resume_smoke.py", "No user-managed worker terminal is required")
    require_contains("scripts/taskboard_cold_resume_acceptance.py", "taskboard-cold-resume-acceptance")
    require_contains("scripts/taskboard_cold_resume_acceptance.py", "cold_resume_readiness")
    require_contains("scripts/taskboard_cold_resume_acceptance.py", "smoke/test/demo")
    require_contains("scripts/taskboard_cold_resume_acceptance.py", "checkout owner conflict")
    require_contains("scripts/taskboard_cold_resume_acceptance.py", "read-only")
    require_contains("scripts/taskboard_framework_readiness.py", "taskboard-framework-readiness")
    require_contains("scripts/taskboard_framework_readiness.py", "field-verification-required")
    require_contains("scripts/taskboard_framework_readiness.py", "real overnight field run")
    require_contains("scripts/taskboard_framework_readiness.py", "T0 manager-only framework readiness audit")
    require_contains("scripts/taskboard_framework_readiness.py", "taskboard_overnight_field_run.py")
    require_contains("scripts/taskboard_overnight_field_run.py", "taskboard-overnight-field-run")
    require_contains("scripts/taskboard_overnight_field_run.py", "must not launch workers")
    require_contains("scripts/taskboard_overnight_field_run.py", "overnight-field-run.json")
    require_contains("scripts/taskboard_overnight_field_run.py", "cold_resume_acceptance_state")
    require_contains("scripts/taskboard_overnight_field_run.py", "live_milestone_acceptance_state")
    require_contains("scripts/taskboard_overnight_field_run.py", "next_command")
    require_contains("tests/test_taskboard_overnight_field_run.py", 'assertNotIn("<field-run-id>", initial["next_command"])')
    require_contains("scripts/taskboard_overnight_field_run.py", "ready-to-resume")
    require_contains("scripts/taskboard_overnight_field_run.py", "ready-to-verify")
    require_contains("scripts/taskboard_t0_boundary_smoke.py", "taskboard-t0-boundary-smoke")
    require_contains("scripts/taskboard_t0_boundary_smoke.py", "worker-owned context file(s) created")
    require_contains("scripts/taskboard_t0_boundary_smoke.py", "T0 dry-run created only T0 control-plane and target files")
    require_contains("scripts/taskboard_subagent_smoke.py", "taskboard-subagent-smoke")
    require_contains("scripts/taskboard_subagent_smoke.py", "subagent_next_payload")
    require_contains("scripts/taskboard_subagent_smoke.py", "subagent_ack_payload")
    require_contains("scripts/taskboard_subagent_smoke.py", "subagent_retry_payload")
    require_contains("scripts/taskboard_subagent_smoke.py", "T0 generated isolated native-subagent prompts without launcher commands")
    require_contains("scripts/taskboard_subagents.py", "taskboard-subagent-plan")
    require_contains("scripts/taskboard_subagents.py", "spawn-native-subagent")
    require_contains("scripts/taskboard_subagents.py", "subagent_acceptance_command")
    require_contains("scripts/taskboard_subagents.py", "result_receipt")
    require_contains("scripts/taskboard_subagents.py", "summary_hash")
    require_contains("tests/test_taskboard_cli.py", "test_subagent_plan_returns_single_t0_dispatch_action")
    require_contains("tests/test_taskboard_cli.py", "test_subagent_plan_surfaces_active_failed_and_complete_actions")
    require_contains("tests/test_taskboard_subagent_acceptance.py", "test_result_evidence_mode_passes_with_native_result_metadata")
    require_contains("tests/test_taskboard_subagent_acceptance.py", "test_result_evidence_mode_rejects_summary_hash_mismatch")
    require_contains("scripts/taskboard_subagent_acceptance.py", "taskboard-subagent-acceptance")
    require_contains("scripts/taskboard_subagent_acceptance.py", "--require-real-agent-ids")
    require_contains("scripts/taskboard_subagent_acceptance.py", "--require-spawn-evidence")
    require_contains("scripts/taskboard_subagent_acceptance.py", "--require-result-evidence")
    require_contains("scripts/taskboard_subagent_acceptance.py", "spawn_receipt missing")
    require_contains("scripts/taskboard_subagent_acceptance.py", "result_receipt missing")
    require_contains("scripts/taskboard_subagent_acceptance.py", "completion_receipt missing")
    require_contains("scripts/taskboard_subagent_acceptance.py", "spawn_tool missing")
    require_contains("scripts/taskboard_subagent_acceptance.py", "agent_nickname missing")
    require_contains("scripts/taskboard_subagent_acceptance.py", "prompt_hash mismatch")
    require_contains("scripts/taskboard_subagent_acceptance.py", "result summary_hash mismatch")
    require_contains("scripts/taskboard_subagent_acceptance.py", "completion_receipt native_status is not completed")
    require_contains("scripts/taskboard_subagent_acceptance.py", "prompt includes skill, role, boundary, and loop gates")
    require_contains("scripts/taskboard_subagent_acceptance.py", "placeholder evidence")
    require_contains("scripts/taskboard_live_milestone_acceptance.py", "taskboard-live-milestone-acceptance")
    require_contains("scripts/taskboard_live_milestone_acceptance.py", "T0-managed milestone")
    require_contains("scripts/taskboard_live_milestone_acceptance.py", "placeholder evidence")
    require_contains("scripts/taskboard_live_milestone_acceptance.py", "checkout owner conflict")
    require_contains("scripts/taskboard_live_milestone_acceptance.py", "read-only")
    require_contains("tests/test_taskboard_cli.py", "test_move_archives_completed_task_under_archive_directory")
    require_contains("tests/test_taskboard_subagent_smoke.py", "test_smoke_proves_subagent_ack_done_retry_control_plane")
    require_contains("tests/test_taskboard_cold_resume_smoke.py", "test_smoke_proves_fresh_worker_recovers_active_task_from_board")
    require_contains("tests/test_taskboard_cold_resume_acceptance.py", "test_acceptance_passes_with_real_t0_progress_and_cold_resume_evidence")
    require_contains("tests/test_taskboard_cold_resume_acceptance.py", "test_acceptance_fails_for_smoke_mode_and_missing_current_instruction")
    require_contains("tests/test_taskboard_framework_readiness.py", "test_readiness_maps_user_goal_to_evidence_and_remaining_field_gap")
    require_contains("tests/test_taskboard_framework_readiness.py", "test_readiness_text_output_names_missing_field_run")
    require_contains("tests/test_taskboard_framework_readiness.py", "test_readiness_accepts_verified_overnight_field_run_marker")
    require_contains("tests/test_taskboard_overnight_field_run.py", "test_start_resume_and_verify_records_real_overnight_evidence")
    require_contains("tests/test_taskboard_overnight_field_run.py", "test_resume_rejects_too_short_elapsed_time")
    require_contains("tests/test_taskboard_overnight_field_run.py", "test_status_reports_next_action_across_overnight_stages")
    require_contains("tests/test_taskboard_overnight_field_run.py", "test_status_reports_start_gate_readiness_and_blockers")
    require_contains("tests/test_taskboard_overnight_field_run.py", "test_status_guides_blocked_field_run_back_to_t0_preparation")
    require_contains("tests/test_taskboard_overnight_field_run.py", "test_status_prepare_command_uses_saved_t0_goal_when_available")
    require_contains("tests/test_taskboard_overnight_field_run.py", "test_status_accepts_format_after_subcommand_for_recovery_diagnostics")
    require_contains("scripts/taskboard_overnight_field_run.py", "next_ready")
    require_contains("scripts/taskboard_overnight_field_run.py", "next_blockers")
    require_contains("scripts/taskboard_overnight_field_run.py", "next_gate")
    require_contains("scripts/taskboard_overnight_field_run.py", "prepare_command")
    require_contains("scripts/taskboard_overnight_field_run.py", "read_runtime_goal")
    require_contains("scripts/taskboard_overnight_field_run.py", "do not manage T1/T2/T3 directly")
    require_contains("scripts/taskboard_overnight_field_run.py", "default=SUPPRESS")
    require_contains("tests/test_taskboard_t0_boundary_smoke.py", "test_smoke_passes_when_t0_startup_only_writes_control_plane_files")
    require_contains("tests/test_taskboard_t0_boundary_smoke.py", "test_smoke_fails_when_t0_creates_worker_owned_context")
    require_contains("tests/test_taskboard_subagent_acceptance.py", "test_acceptance_passes_completed_subagent_dispatch_records")
    require_contains("tests/test_taskboard_subagent_acceptance.py", "test_real_agent_id_mode_rejects_smoke_placeholders")
    require_contains("tests/test_taskboard_subagent_acceptance.py", "test_spawn_evidence_mode_requires_native_spawn_metadata")
    require_contains("tests/test_taskboard_subagent_acceptance.py", "test_spawn_evidence_mode_passes_with_native_spawn_metadata")
    require_contains("tests/test_taskboard_subagent_acceptance.py", "test_spawn_evidence_mode_rejects_prompt_hash_mismatch")
    require_contains("tests/test_taskboard_live_milestone_acceptance.py", "test_acceptance_passes_when_live_t0_managed_milestone_has_all_evidence")
    require_contains("tests/test_taskboard_live_milestone_acceptance.py", "test_acceptance_rejects_smoke_placeholders_and_checkout_conflict")
    require_contains("README.md", "python scripts/taskboard_e2e_smoke.py")
    require_contains("README.md", "python scripts/taskboard_cold_resume_smoke.py")
    require_contains("README.md", "python scripts/taskboard_cold_resume_acceptance.py --root .")
    require_contains("README.md", "python scripts/taskboard_overnight_field_run.py --root . start --run-id")
    require_contains("README.md", "python scripts/taskboard_overnight_field_run.py --root . resume")
    require_contains("README.md", "python scripts/taskboard_overnight_field_run.py --root . verify")
    require_contains("README.md", "python scripts/taskboard_overnight_field_run.py --root . status")
    require_contains("README.md", "The status `next_command` omits `--run-id`")
    require_contains("README.md", 'status --goal "<user goal>"')
    require_contains("README.md", "下一关卡是否 ready")
    require_contains("README.md", "T0 prepare command")
    require_contains("README.md", "prepare command 会复用保存目标")
    require_contains("README.md", "python scripts/taskboard_framework_readiness.py --root .")
    require_contains("README.md", "python scripts/taskboard_t0_boundary_smoke.py")
    require_contains("README.md", "python scripts/taskboard_subagent_smoke.py")
    require_contains("README.md", "python scripts/taskboard_subagent_acceptance.py --root . --require-real-agent-ids --require-spawn-evidence")
    require_contains("README.md", "python scripts/taskboard_live_milestone_acceptance.py --root .")
    require_contains("USER-MANUAL.md", "python scripts/taskboard_e2e_smoke.py")
    require_contains("USER-MANUAL.md", "python scripts/taskboard_cold_resume_smoke.py")
    require_contains("USER-MANUAL.md", "python scripts/taskboard_cold_resume_acceptance.py --root .")
    require_contains("USER-MANUAL.md", "python scripts/taskboard_overnight_field_run.py --root . start --run-id")
    require_contains("USER-MANUAL.md", "python scripts/taskboard_overnight_field_run.py --root . resume")
    require_contains("USER-MANUAL.md", "python scripts/taskboard_overnight_field_run.py --root . verify")
    require_contains("USER-MANUAL.md", "python scripts/taskboard_overnight_field_run.py --root . status")
    require_contains("USER-MANUAL.md", "The status `next_command` omits `--run-id`")
    require_contains("USER-MANUAL.md", 'status --goal "<user goal>"')
    require_contains("USER-MANUAL.md", "python scripts/taskboard_framework_readiness.py --root .")
    require_contains("USER-MANUAL.md", "python scripts/taskboard_t0_boundary_smoke.py")
    require_contains("USER-MANUAL.md", "python scripts/taskboard_subagent_smoke.py")
    require_contains("USER-MANUAL.md", "python scripts/taskboard_subagent_acceptance.py --root . --require-real-agent-ids --require-spawn-evidence")
    require_contains("USER-MANUAL.md", "python scripts/taskboard_live_milestone_acceptance.py --root .")
    require_contains("README.md", "completion sentinel/dev-log")
    require_contains("README.md", "progress 进入 `complete`")
    require_contains("USER-MANUAL.md", "completion audit 进入 `complete-ready`")
    require_contains("USER-MANUAL.md", "progress 进入 `complete`")
    require_contains("scripts/taskboard_loop.py", "T0 supervisor-only")
    require_contains("scripts/taskboard_start.py", "DEFAULT_AGENT_TEMPLATE")
    require_contains("scripts/taskboard_start.py", """DEFAULT_AGENT_TEMPLATE = 'claude "{target}"'""")
    require_contains("scripts/taskboard_loop.py", """default_agent_template = 'claude "{target}"'""")
    require_contains("scripts/taskboard_progress.py", """DEFAULT_RESUME_AGENT_TEMPLATE = 'claude "{target}"'""")
    require_contains("scripts/taskboard.py", """default='claude "{target}"'""")
    require_contains("scripts/taskboard_t0.py", """default='claude "{target}"'""")
    require_contains("scripts/taskboard_sessions.py", """default='claude "{target}"'""")
    require_contains("scripts/taskboard_start.py", 'default="windows-terminal"')
    require_contains("scripts/taskboard_start.py", "--execute-launches")
    require_contains("scripts/taskboard_start.py", "--fallback-launcher")
    require_contains("scripts/taskboard_start.py", "--auto")
    require_contains("scripts/taskboard_start.py", "--dry-run")
    require_contains("scripts/taskboard_start.py", "T0 one-command auto mode")
    require_contains("scripts/taskboard_start.py", "starter_metadata")
    require_contains("scripts/taskboard_start.py", "write_state_snapshot")
    require_contains("scripts/taskboard_start.py", "KeyboardInterrupt")
    require_contains("scripts/taskboard_start.py", "taskboard-t0-interruption")
    require_contains("scripts/taskboard_start.py", "taskboard-t0-config-error")
    require_contains("scripts/taskboard_start.py", "build_config_error_payload")
    require_contains("scripts/taskboard_start.py", "build_launch_probe")
    require_contains("scripts/taskboard_start.py", "Resume T0 with resume_command")
    require_contains("scripts/taskboard_start.py", "persist_interruption_payload")
    require_contains("scripts/taskboard_start.py", "append_event_log")
    require_contains("scripts/taskboard_start.py", "write_runtime_goal")
    require_contains("scripts/taskboard_progress.py", 'state == "interrupted"')
    require_contains("scripts/taskboard_progress.py", 'fallback_state = "interrupted"')
    require_contains("scripts/taskboard_progress.py", 'latest_event_payload.get("goal")')
    require_contains("scripts/taskboard_loop.py", 'payload["dispatch"].get("state") == "needs-goal"')
    require_contains("scripts/taskboard_progress.py", "starter_mode")
    require_contains("scripts/taskboard_progress.py", "resume_config")
    require_contains("README.md", "auto_mode")
    require_contains("README.md", "starter_mode")
    require_contains("README.md", "resume_config")
    require_contains("README.md", "needs-goal")
    require_contains("README.md", "taskboard-t0-interruption")
    require_contains("README.md", "KeyboardInterrupt")
    require_contains("README.md", "即使终端输出丢失")
    require_contains("README.md", "latest event 的 `interrupted` 状态")
    require_contains("scripts/taskboard_start.py", "default_event_log_file")
    require_contains("scripts/taskboard_start.py", "--no-event-log")
    require_contains("scripts/taskboard_start.py", "run_loop")
    require_contains("scripts/taskboard_t0.py", "runtime_goal_file")
    require_contains("scripts/taskboard_t0.py", "taskboard-t0-goal")
    require_contains("README.md", ".taskboard/t0/goal.json")
    require_contains("scripts/taskboard_loop.py", "build_assignment")
    require_contains("scripts/taskboard_progress.py", "taskboard-t0-progress")
    require_contains("scripts/taskboard_watchdog.py", "taskboard-t0-watchdog")
    require_contains("scripts/taskboard_watchdog.py", "report_watchdog")
    require_contains("scripts/taskboard_watchdog.py", "do not manage T1/T2/T3 directly")
    require_contains("scripts/taskboard_watchdog.py", "it must not launch or manage T1/T2/T3 directly")
    require_contains("scripts/taskboard_progress.py", "completion_ready")
    require_contains("scripts/taskboard_progress.py", "completion_audit_state")
    require_contains("scripts/taskboard_progress.py", "completion_missing_evidence")
    require_contains("scripts/taskboard_progress.py", "T0 will wake T1")
    require_contains("scripts/taskboard_progress.py", "assignment_role")
    require_contains("scripts/taskboard_progress.py", "assignment_reason")
    require_contains("scripts/taskboard_progress.py", "T0 will reissue target")
    require_contains("scripts/taskboard_progress.py", "queue_metrics")
    require_contains("scripts/taskboard_progress.py", "cold_resume_readiness")
    require_contains("scripts/taskboard_progress.py", "cold_resume_state")
    require_contains("scripts/taskboard_progress.py", "cold_resume_missing_evidence")
    require_contains("scripts/taskboard_progress.py", "Current Instruction")
    require_contains("scripts/taskboard_progress.py", "scoped git status")
    require_contains("tests/test_taskboard_progress.py", "test_progress_surfaces_cold_resume_readiness_for_active_worker_task")
    require_contains("README.md", "cold_resume_readiness")
    require_contains("USER-MANUAL.md", "cold_resume_readiness")
    require_contains("references/taskboard-template.md", "cold_resume_readiness")
    require_contains("scripts/taskboard_progress.py", "report_health")
    require_contains("scripts/taskboard_progress.py", "queue_metrics_active_count")
    require_contains("scripts/taskboard_progress.py", "build_t0_supervisor_freshness")
    require_contains("scripts/taskboard_progress.py", "t0_supervisor_state")
    require_contains("scripts/taskboard_progress.py", "t0_supervisor_age_seconds")
    require_contains("scripts/taskboard_progress.py", "t0_supervisor_stale_after_seconds")
    require_contains("scripts/taskboard_progress.py", "T0 queue metrics")
    require_contains("scripts/taskboard_progress.py", "No user action required")
    require_contains("scripts/taskboard_progress.py", "T0 launch/recovery failed")
    require_contains("scripts/taskboard_progress.py", "config-error")
    require_contains("scripts/taskboard_progress.py", "T0 configuration failed")
    require_contains("scripts/taskboard_progress.py", "latest_event_failure_list")
    require_contains("scripts/taskboard_progress.py", "latest_event_launch_failure_count")
    require_contains("scripts/taskboard_progress.py", "suppressed_launch_count")
    require_contains("scripts/taskboard_progress.py", "latest_event_suppressed_list")
    require_contains("scripts/taskboard_progress.py", "latest_event_suppressed_count")
    require_contains("scripts/taskboard_progress.py", "decision_command")
    require_contains("scripts/taskboard_progress.py", "taskboard_decide.py")
    require_contains("scripts/taskboard_progress.py", "do not perform design")
    require_contains("README.md", "taskboard-t0-watchdog")
    require_contains("README.md", "python scripts/taskboard_watchdog.py --root . --execute")
    require_contains("USER-MANUAL.md", "taskboard-t0-watchdog")
    require_contains("USER-MANUAL.md", "python scripts/taskboard_watchdog.py --root . --execute")
    require_contains("README.md", "T0 launch/recovery failed")
    require_contains("README.md", "fix T0 launcher configuration")
    require_contains("README.md", "not to manage T1/T2/T3 directly")
    require_contains("README.md", "config-error")
    require_contains("README.md", "`error` text")
    require_contains("README.md", "stops launching further worker commands after the first launcher failure")
    require_contains("README.md", "python scripts/taskboard_completion.py --root .")
    require_contains("README.md", "python scripts/taskboard_stopgates.py --root .")
    require_contains("README.md", "python scripts/taskboard_decide.py --root . --decision")
    require_contains("README.md", "decision_command")
    require_contains("README.md", "让 T1 根据用户决策继续修订")
    require_contains("README.md", "healthy roles are not relaunched")
    require_contains("README.md", "--launch-lease-seconds 300")
    require_contains("README.md", ".taskboard/t0/launches.json")
    require_contains("README.md", "completion audit is `complete-ready`")
    require_contains("README.md", "completion-audit-missing-evidence")
    require_contains("README.md", "completion_missing_evidence")
    require_contains("README.md", "T0 will wake T1")
    require_contains("scripts/taskboard_t0.py", "report_completion")
    require_contains("scripts/taskboard_t0.py", "completion-audit-missing-evidence")
    require_contains("scripts/taskboard_loop.py", "pending-ack")
    require_contains("scripts/taskboard_loop.py", "pending-ack-expired")
    require_contains("scripts/taskboard_loop.py", "assignment_pending_age_seconds")
    require_contains("scripts/taskboard_loop.py", "assignment_watch")
    require_contains("scripts/taskboard_loop.py", "lease-expired")
    require_contains("scripts/taskboard_loop.py", "--assignment-lease-seconds")
    require_contains("scripts/taskboard_loop.py", "--launch-lease-seconds")
    require_contains("scripts/taskboard_loop.py", "choose_executable_launch_commands")
    require_contains("scripts/taskboard_loop.py", "stop_gate_report")
    require_contains("scripts/taskboard_loop.py", "user-stop-gate")
    require_contains("scripts/taskboard_loop.py", "decision_command")
    require_contains("scripts/taskboard_loop.py", "taskboard_decide.py")
    require_contains("scripts/taskboard_loop.py", "--no-stop-on-stop-gate")
    require_contains("scripts/taskboard_start.py", "--no-stop-on-stop-gate")
    require_contains("scripts/taskboard_loop.py", "planned_launch_commands")
    require_contains("scripts/taskboard_loop.py", "taskboard-t0-launch-state")
    require_contains("scripts/taskboard_loop.py", "launch-lease-active")
    require_contains("scripts/taskboard_loop.py", "--no-stop-on-complete")
    require_contains("scripts/taskboard_loop.py", "--state-file")
    require_contains("scripts/taskboard_loop.py", "--no-state-file")
    require_contains("scripts/taskboard_loop.py", "--event-log-file")
    require_contains("scripts/taskboard_loop.py", "--no-event-log")
    require_contains("scripts/taskboard_loop.py", "taskboard-t0-supervisor-event")
    require_contains("scripts/taskboard_loop.py", "append-only event log")
    require_contains("scripts/taskboard_loop.py", "launch_failure_count")
    require_contains("scripts/taskboard_loop.py", "launch_failures")
    require_contains("scripts/taskboard_loop.py", "execute_fallback_launchers")
    require_contains("scripts/taskboard_loop.py", "fallback_launch_count")
    require_contains("scripts/taskboard_loop.py", "fallback_launch_recovered")
    require_contains("scripts/taskboard_loop.py", "stalled_recoveries")
    require_contains("scripts/taskboard_loop.py", "stalled_recovery_count")
    require_contains("scripts/taskboard_loop.py", "role_liveness_state")
    require_contains("scripts/taskboard_loop.py", '"error"')
    require_contains("scripts/taskboard_loop.py", "T0 launch/recovery failed")
    require_contains("scripts/taskboard_loop.py", "fix the T0 launcher configuration")
    require_contains("scripts/taskboard_loop.py", "do not manage T1/T2/T3 directly")
    require_contains("scripts/taskboard_loop.py", "if completed.returncode != 0")
    require_contains("scripts/taskboard_loop.py", "suppressed_launch_count")
    require_contains("scripts/taskboard_loop.py", "auto_mode")
    require_contains("scripts/taskboard_loop.py", "starter_mode")
    require_contains("scripts/taskboard_loop.py", "resume_config")
    require_contains("scripts/taskboard_loop.py", '"resume_config": resume_config_payload')
    require_contains("scripts/taskboard_loop.py", "completion_missing_evidence")
    require_contains("scripts/taskboard_loop.py", "completion_user_action")
    require_contains("scripts/taskboard_loop.py", "assignment_role")
    require_contains("scripts/taskboard_loop.py", "assignment_expected_id")
    require_contains("README.md", "launch_failure_count")
    require_contains("README.md", "launch_failures")
    require_contains("README.md", "fallback_launch_count")
    require_contains("README.md", "stalled_recovery_count")
    require_contains("README.md", "stalled_recoveries")
    require_contains("README.md", "--fallback-launcher")
    require_contains("README.md", "config-error")
    require_contains("README.md", "suppressed_launch_count")
    require_contains("README.md", "latest event 的 `suppressed_launches`")
    require_contains("README.md", "events.jsonl` also records `auto_mode`")
    require_contains("README.md", "completion_missing_evidence")
    require_contains("README.md", "completion_user_action")
    require_contains("README.md", "assignment_role")
    require_contains("README.md", "assignment_reason")
    require_contains("README.md", "assignment_expected_id")
    require_contains("README.md", "pending-ack-expired")
    require_contains("README.md", "assignment_pending_age_seconds")
    require_contains("README.md", "queue_metrics")
    require_contains("README.md", "queue_metrics_active_count")
    require_contains("README.md", "current taskboard live health")
    require_contains("README.md", "T1/T2/T3 队列规模")
    require_contains("README.md", "t0_supervisor_state")
    require_contains("README.md", "t0_supervisor_age_seconds")
    require_contains("README.md", "t0_supervisor_stale_after_seconds")
    require_contains("README.md", "恢复 T0，而不是管理 T1/T2/T3")
    require_contains("scripts/taskboard_progress.py", "event_count")
    require_contains("scripts/taskboard_progress.py", "latest_event")
    require_contains("scripts/taskboard_progress.py", "latest_event_state")
    require_contains("scripts/taskboard_progress.py", "latest_event_dispatch_state")
    require_contains("scripts/taskboard_progress.py", "latest_event_next_role")
    require_contains("scripts/taskboard_progress.py", "latest_event_task")
    require_contains("scripts/taskboard_progress.py", "latest_event_assignment_state")
    require_contains("scripts/taskboard_progress.py", "latest_event_auto_mode")
    require_contains("scripts/taskboard_progress.py", "latest_event_starter_mode")
    require_contains("scripts/taskboard_progress.py", "auto_mode: bool = True")
    require_contains("scripts/taskboard_progress.py", "latest_event_assignment_role")
    require_contains("scripts/taskboard_progress.py", "latest_event_assignment_expected_id")
    require_contains("scripts/taskboard_progress.py", "assignment_pending_age_seconds")
    require_contains("scripts/taskboard_progress.py", "latest_event_launch_failure_count")
    require_contains("scripts/taskboard_progress.py", "latest_event_launch_failure_output")
    require_contains("scripts/taskboard_progress.py", "fallback_launch_recovered")
    require_contains("scripts/taskboard_progress.py", "fallback_launchers")
    require_contains("scripts/taskboard_progress.py", "stalled_recovery_count")
    require_contains("scripts/taskboard_progress.py", "resume_command")
    require_contains("scripts/taskboard_progress.py", "--fallback-launcher")
    require_contains("scripts/taskboard_progress.py", "--agent-template")
    require_contains("scripts/taskboard_progress.py", "target_files_enabled")
    require_contains("scripts/taskboard_progress.py", "--no-target-files")
    require_contains("scripts/taskboard_loop.py", "target_files_enabled")
    require_contains("README.md", ".taskboard/t0/events.jsonl")
    require_contains("README.md", "--launcher none")
    require_contains("README.md", "--fallback-launcher")
    require_contains("README.md", "--no-target-files")
    require_contains("README.md", "auto vs dry-check")
    require_contains("references/role-t0.md", "target-file-mode")
    require_contains("references/role-t0.md", "fallback-launcher")
    require_contains("references/role-t0.md", "fallback_launch_recovered=True")
    require_contains("references/role-t0.md", "pending-ack-expired")
    require_contains("references/role-t0.md", "assignment_pending_age_seconds")
    require_contains("references/role-t0.md", "stalled_recovery_count")
    require_contains("references/role-t0.md", "stalled_recoveries")
    require_contains("references/role-t0.md", "auto vs dry-check")
    for role_reference in (
        "references/role-t1.md",
        "references/role-t2.md",
        "references/role-t3.md",
    ):
        require_contains(role_reference, "### External Tool Boundaries")
        require_contains(role_reference, "Use GitHub tooling for repository, PR, issue, release, and CI-check work")
        require_contains(role_reference, "Use Chrome/Browser tooling for web UI inspection")
        require_contains(role_reference, "Use Computer Use only for local desktop or GUI workflows")
        require_contains(role_reference, "Do not ask the user to operate these tools for routine role work")
        require_contains(role_reference, "Respect role boundaries when using external tools")
    require_contains("README.md", "latest_event_state")
    require_contains("README.md", "latest_event_dispatch_state")
    require_contains("README.md", "latest_event_next_role")
    require_contains("README.md", "top-level JSON progress")
    require_contains("README.md", "latest event `auto_mode`, `starter_mode`, `next_role`, `task`, and `assignment_*`")
    require_contains("README.md", "confirm one-command T0 auto entry")
    require_contains("README.md", "current taskboard has a stop gate")
    require_contains("README.md", "state=stop-gate")
    require_contains("README.md", "current completion audit is ready")
    require_contains("README.md", "state=complete")
    require_contains("README.md", "dispatch_state=needs-goal")
    require_contains("README.md", "state=needs-goal")
    require_contains("README.md", "latest_event_assignment_role")
    require_contains("README.md", "latest_event_assignment_expected_id")
    require_contains("README.md", "latest_event_launch_failure_count")
    require_contains("README.md", "latest_event_launch_failure_output")
    require_contains("README.md", "fallback_launch_recovered=True")
    require_contains("README.md", "latest event 的 `launch_failures`")
    require_contains("README.md", "resume_command")
    require_contains("README.md", "agent-template")
    require_contains("README.md", 'claude "{target}"')
    require_contains("README.md", "Codex 或其他客户端仍可通过")
    require_contains("README.md", "--agent-preflight-command")
    require_contains("README.md", "--no-agent-preflight")
    require_contains("README.md", "agent preflight command failed")
    require_contains("README.md", "latest event")
    require_contains("README.md", 'python scripts/taskboard_start.py --goal "<user goal>"')
    require_contains("README.md", "--dry-run --iterations 1 --launcher none")
    require_contains("README.md", "suppresses worker launch/target/assignment")
    require_contains("README.md", "asks the summarized question through T0 only")
    require_contains("README.md", "--no-stop-on-stop-gate")
    require_contains("README.md", "stops after one `stop-gate` iteration")
    require_contains("README.md", "The stop-gate loop output includes `decision_command`")
    require_contains("scripts/taskboard_loop.py", "--target-dir")
    require_contains("scripts/taskboard_loop.py", "--no-target-files")
    require_contains("scripts/taskboard_loop.py", "write_role_target_files")
    require_contains("scripts/taskboard_t0.py", "taskboard-role-target")
    require_contains("scripts/taskboard_loop.py", ".taskboard")
    require_contains("scripts/taskboard_loop.py", "taskboard-t0-supervisor-state")
    require_contains("scripts/taskboard_loop.py", "stop_on_complete")
    require_contains("scripts/taskboard_next.py", "has_goal_complete_sentinel")
    require_contains("scripts/taskboard_next.py", "goal-complete-sentinel")
    require_contains("scripts/taskboard_loop.py", "--execute-launches")
    require_contains("scripts/taskboard_loop.py", "validate_agent_preflight")
    require_contains("scripts/taskboard_loop.py", "--agent-preflight-command")
    require_contains("scripts/taskboard_loop.py", "launch_failure_is_spawn_refusal")
    require_contains("scripts/taskboard_loop.py", "build_launch_probe")
    require_contains("scripts/taskboard_loop.py", "launch_probe_recommended_backend")
    require_contains("scripts/taskboard_loop.py", "spawn-refused")
    require_contains("scripts/taskboard_loop.py", "agent-preflight-spawn-refused")
    require_contains("scripts/taskboard_loop.py", "manual_launch_files")
    require_contains("scripts/taskboard_loop.py", "subagent_fallback")
    require_contains("scripts/taskboard_loop.py", "taskboard-subagent-fallback")
    require_contains("scripts/taskboard_loop.py", "subagent_fallback_available")
    require_contains("scripts/taskboard_loop.py", "taskboard-subagent-fallback-packet")
    require_contains("scripts/taskboard_loop.py", "default_subagent_fallback_file")
    require_contains("scripts/taskboard_loop.py", "subagent-fallback.json")
    require_contains("scripts/taskboard_loop.py", "subagent_prompt_roles")
    require_contains("scripts/taskboard_progress.py", "subagent_fallback_available")
    require_contains("scripts/taskboard_progress.py", "subagent_fallback_packet_available")
    require_contains("scripts/taskboard_progress.py", "subagent_fallback_packet_file")
    require_contains("scripts/taskboard_progress.py", "subagent_prompt_roles")
    require_contains("scripts/taskboard_progress.py", "subagent_dispatched_roles")
    require_contains("scripts/taskboard_progress.py", "subagent_pending_roles")
    require_contains("scripts/taskboard_progress.py", "subagent_completed_roles")
    require_contains("scripts/taskboard_progress.py", "subagent_failed_roles")
    require_contains("scripts/taskboard_progress.py", "subagent_control_state")
    require_contains("scripts/taskboard_progress.py", "subagent_control_next_role")
    require_contains("scripts/taskboard_progress.py", "subagent_plan_command")
    require_contains("scripts/taskboard_progress.py", "subagent_next_command")
    require_contains("scripts/taskboard_progress.py", "subagent_ack_command")
    require_contains("scripts/taskboard_progress.py", "--spawn-tool")
    require_contains("scripts/taskboard_progress.py", "--agent-nickname")
    require_contains("scripts/taskboard_progress.py", "subagent_done_command")
    require_contains("scripts/taskboard_progress.py", "subagent_fail_command")
    require_contains("scripts/taskboard_progress.py", "subagent_retry_commands")
    require_contains("scripts/taskboard_progress.py", "subagent_control_boundary")
    require_contains("scripts/taskboard_progress.py", "launch_probe_recommended_backend")
    require_contains("scripts/taskboard_progress.py", "latest_event_launch_probe_recommended_backend")
    require_contains("scripts/taskboard.py", "subagent")
    require_contains("scripts/taskboard.py", "subagent_ack_payload")
    require_contains("scripts/taskboard.py", "--spawn-tool")
    require_contains("scripts/taskboard.py", "--agent-nickname")
    require_contains("scripts/taskboard.py", "subagent_result_payload")
    require_contains("scripts/taskboard.py", "subagent_retry_payload")
    require_contains("scripts/taskboard_subagents.py", "taskboard-subagent-dispatch-state")
    require_contains("scripts/taskboard_subagents.py", "taskboard-subagent-next")
    require_contains("scripts/taskboard_subagents.py", "taskboard-subagent-plan")
    require_contains("scripts/taskboard_subagents.py", "taskboard-subagent-ack")
    require_contains("scripts/taskboard_subagents.py", "spawn_receipt")
    require_contains("scripts/taskboard_subagents.py", "result_receipt")
    require_contains("scripts/taskboard_subagents.py", "completion_receipt")
    require_contains("scripts/taskboard_subagents.py", "prompt_hash")
    require_contains("scripts/taskboard_subagents.py", "taskboard-subagent-result")
    require_contains("scripts/taskboard_subagents.py", "taskboard-subagent-retry")
    require_contains("scripts/taskboard_subagents.py", "retry-pending")
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_subagents.py"')
    require_contains("scripts/taskboard_t0.py", "write_manual_windows_launch_scripts")
    require_contains("scripts/taskboard_t0.py", "open-tabs.ps1")
    require_contains("scripts/taskboard_t0.py", "launch-role.ps1")
    require_contains("scripts/taskboard_t0.py", "taskboard-subagent-backend")
    require_contains("scripts/taskboard_t0.py", "build_subagent_prompts")
    require_contains("scripts/taskboard_t0.py", "Do not inherit T0 private reasoning")
    require_contains("scripts/taskboard_loop.py", "taskboard-subagent-loop-control")
    require_contains("scripts/taskboard_loop.py", "subagent_ack_payload")
    require_contains("scripts/taskboard_loop.py", "subagent_result_payload")
    require_contains("scripts/taskboard_loop.py", "subagent_control_state")
    require_contains("scripts/taskboard_loop.py", "--native-spawn-receipt-json")
    require_contains("scripts/taskboard_loop.py", "--native-spawn-receipt-file")
    require_contains("scripts/taskboard_loop.py", "--native-result-receipt-json")
    require_contains("scripts/taskboard_loop.py", "--native-result-receipt-file")
    require_contains("scripts/taskboard_loop.py", "load_native_receipt_json")
    require_contains("tests/test_taskboard_loop.py", "test_loop_emits_subagent_control_plan_after_spawn_refusal")
    require_contains("tests/test_taskboard_loop.py", "test_loop_records_injected_native_spawn_receipt_and_advances_subagent_plan")
    require_contains("tests/test_taskboard_loop.py", "test_loop_records_injected_native_result_receipt_and_advances_subagent_plan")
    require_contains("tests/test_taskboard_loop.py", "test_cli_imports_native_spawn_receipt_json_and_advances_subagent_plan")
    require_contains("tests/test_taskboard_loop.py", "test_cli_imports_native_result_receipt_json_and_advances_subagent_plan")
    require_contains("tests/test_taskboard_loop.py", "test_cli_rejects_invalid_native_receipt_json")
    require_contains("scripts/taskboard_start.py", "--agent-preflight-command")
    require_contains("scripts/taskboard_loop.py", "do not perform design")
    require_contains("scripts/taskboard_t0.py", 'default="terminal"')
    require_contains("scripts/taskboard_t0.py", "T0 manager-only")
    require_contains("scripts/taskboard_t0.py", "--launcher")
    require_contains("scripts/taskboard_t0.py", "{target_file}")
    require_contains("scripts/taskboard_t0.py", "agent-template references {target_file}")
    require_contains("scripts/taskboard_t0.py", "enable target files or use {target}")
    require_contains("scripts/taskboard_t0.py", "default_target_dir")
    require_contains("scripts/taskboard_t0.py", "build_launch_commands")
    require_contains("scripts/taskboard_t0.py", "build_session_manifest")
    require_contains("scripts/taskboard_t0.py", 'f"taskboard-{role}"')
    require_contains("scripts/taskboard_t0.py", "taskboard.py --root . alive {role}")
    require_contains("scripts/taskboard_t0.py", "taskboard.py --root . cycle {role} --sleep-seconds 120")
    require_contains("scripts/taskboard_t0.py", "taskboard_sessions.py --root . heartbeat --role {role}")
    require_contains("scripts/taskboard_t0.py", "--assignment-id {role}:{task_name}")
    require_contains("scripts/taskboard_t0.py", "Role runtime contract")
    require_contains("scripts/taskboard_t0.py", "assigned_role: {role}")
    require_contains("scripts/taskboard_t0.py", "managed_by: T0")
    require_contains("scripts/taskboard_t0.py", "do not rely on another role's chat context")
    require_contains("scripts/taskboard_t0.py", "Default tooling contract")
    require_contains("scripts/taskboard_t0.py", "Required skills evidence")
    require_contains("scripts/taskboard_t0.py", "Record the tool or skill used")
    require_contains("scripts/taskboard_t0.py", "T0 input boundary")
    require_contains("scripts/taskboard_t0.py", "not T0-authored requirements")
    require_contains("scripts/taskboard_t0.py", "T0_FORBIDDEN_SEED_PATTERNS")
    require_contains("scripts/taskboard_t0.py", "forbidden_seed_patterns")
    require_contains("scripts/taskboard_t0.py", "REQ counts")
    require_contains("scripts/taskboard_t0.py", "priority labels")
    require_contains("scripts/taskboard_t0.py", "interface signatures")
    require_contains("scripts/taskboard_t0.py", "MAP risk sections")
    require_contains("scripts/taskboard_t0.py", "T1 owns requirement decomposition and TASK creation")
    require_contains("scripts/taskboard_t0.py", "taskboard-t0-goal-intake")
    require_contains("scripts/taskboard_t0.py", "goal_intake")
    require_contains("scripts/taskboard_t0.py", "forbidden_fields")
    require_contains("scripts/taskboard_t0.py", "task_splits")
    require_contains("scripts/taskboard_t0.py", "acceptance_criteria")
    require_contains("scripts/taskboard_t0.py", "Startup skill gate")
    require_contains("scripts/taskboard_t0.py", "Before any TASKBOARD action")
    require_contains("scripts/taskboard_t0.py", "Evidence enforcement gate")
    require_contains("scripts/taskboard_t0.py", "Missing Required skills evidence is a review failure")
    require_contains("scripts/taskboard_t0.py", "Idle recheck contract")
    require_contains("scripts/taskboard_t0.py", "Do not terminate just because this role queue is empty")
    require_contains("scripts/taskboard_t0.py", "Cross-day cold resume contract")
    require_contains("scripts/taskboard_t0.py", "Do not rely on claude --resume")
    require_contains("scripts/taskboard_t0.py", "same role, same TASK, and same TASK version")
    require_contains("scripts/taskboard_t0.py", "Current Instruction")
    require_contains("scripts/taskboard_t0.py", "T1 MUST use available planning/brainstorming skills")
    require_contains("scripts/taskboard_t0.py", "superpowers:brainstorming")
    require_contains("scripts/taskboard_t0.py", "superpowers:writing-plans")
    require_contains("scripts/taskboard_t0.py", "T2 L2 code reviews default to an independent review tool")
    require_contains("scripts/taskboard_t0.py", "Codex code review")
    require_contains("scripts/taskboard_t0.py", "superpowers:requesting-code-review")
    require_contains("scripts/taskboard_t0.py", "L3 code reviews MUST run dual-pass review")
    require_contains("scripts/taskboard_t0.py", "T3 MUST assess whether the implementation can be split")
    require_contains("scripts/taskboard_t0.py", "Codex native subagents")
    require_contains("scripts/taskboard_t0.py", "available multi-agent tools")
    require_contains("scripts/taskboard_t0.py", "T3 remains responsible for integration, final verification, and commit")
    require_contains("scripts/taskboard_t0.py", "External tool contract")
    require_contains("scripts/taskboard_t0.py", "Use GitHub tooling for repository, PR, issue, release, and CI-check work")
    require_contains("scripts/taskboard_t0.py", "Use Chrome/Browser tooling for web UI inspection")
    require_contains("scripts/taskboard_t0.py", "Use Computer Use only for local desktop or GUI workflows")
    require_contains("scripts/taskboard_t0.py", "Do not ask the user to operate these tools for routine role work")
    require_contains("scripts/taskboard_t0.py", "Respect role boundaries when using external tools")
    require_contains("scripts/taskboard_t0.py", "Worker loop contract")
    require_contains("scripts/taskboard_t0.py", "Continue cycling this role")
    require_contains("scripts/taskboard_t0.py", "refresh your heartbeat at the start of each cycle")
    require_contains("README.md", "Worker loop contract")
    require_contains("README.md", "python scripts/taskboard.py --root . status")
    require_contains("README.md", "python scripts/taskboard.py --root . launch-probe")
    require_contains("README.md", "recommended_backend")
    require_contains("README.md", "launch_probe_recommended_backend")
    require_contains("README.md", "python scripts/taskboard.py --root . cycle T2 --sleep-seconds 120")
    require_contains("README.md", ".taskboard/alive")
    require_contains("README.md", "python scripts/taskboard.py --root . move")
    require_contains("README.md", "非法状态")
    require_contains("README.md", "Default tooling contract")
    require_contains("README.md", "Required skills evidence")
    require_contains("README.md", "open-tabs.ps1")
    require_contains("README.md", "agent_preflight.state")
    require_contains("README.md", "spawn-refused")
    require_contains("README.md", "API Error: 403")
    require_contains("README.md", "taskboard-subagent-fallback")
    require_contains("README.md", "taskboard-subagent-fallback-packet")
    require_contains("README.md", "taskboard-subagent-backend")
    require_contains("README.md", "subagent-fallback.json")
    require_contains("README.md", "subagent_prompts")
    require_contains("README.md", "subagent_fallback_available")
    require_contains("README.md", "subagent_fallback_packet_available")
    require_contains("README.md", "subagent_fallback_packet_file")
    require_contains("README.md", "subagent_prompt_roles")
    require_contains("README.md", "subagent_control_state")
    require_contains("README.md", "--native-spawn-receipt-json")
    require_contains("README.md", "--native-result-receipt-json")
    require_contains("README.md", "subagent_plan_command")
    require_contains("README.md", "subagent_next_command")
    require_contains("README.md", "--require-result-evidence")
    require_contains("README.md", "result_receipt")
    require_contains("README.md", "superpowers:brainstorming")
    require_contains("README.md", "superpowers:requesting-code-review")
    require_contains("README.md", "Codex native subagents")
    require_contains("README.md", "T0 input boundary")
    require_contains("README.md", "not T0-authored requirements")
    require_contains("README.md", "REQ counts")
    require_contains("README.md", "MAP risk sections")
    require_contains("README.md", "taskboard-t0-goal-intake")
    require_contains("README.md", "forbidden fields")
    require_contains("README.md", "forbidden seed patterns")
    require_contains("README.md", "Startup skill gate")
    require_contains("README.md", "Evidence enforcement gate")
    require_contains("README.md", "Idle recheck contract")
    require_contains("README.md", "action=idle-recheck")
    require_contains("README.md", "do not terminate just because this role queue is empty")
    require_contains("README.md", "Cross-day cold resume")
    require_contains("README.md", "cold start is the default correctness path")
    require_contains("README.md", "claude --resume")
    require_contains("README.md", "same role, same TASK, and same TASK version")
    require_contains("README.md", "Current Instruction")
    require_contains("README.md", "External tool contract")
    require_contains("README.md", "GitHub tooling")
    require_contains("README.md", "Chrome/Browser tooling")
    require_contains("README.md", "Computer Use")
    require_contains("USER-MANUAL.md", "Worker loop contract")
    require_contains("USER-MANUAL.md", "python scripts/taskboard.py --root . status")
    require_contains("USER-MANUAL.md", "python scripts/taskboard.py --root . launch-probe")
    require_contains("USER-MANUAL.md", "recommended_backend")
    require_contains("USER-MANUAL.md", "launch_probe_recommended_backend")
    require_contains("USER-MANUAL.md", "python scripts/taskboard.py --root . cycle T2 --sleep-seconds 120")
    require_contains("USER-MANUAL.md", ".taskboard/alive")
    require_contains("USER-MANUAL.md", "python scripts/taskboard.py --root . move")
    require_contains("USER-MANUAL.md", "非法状态")
    require_contains("USER-MANUAL.md", "Default tooling contract")
    require_contains("USER-MANUAL.md", "Required skills evidence")
    require_contains("USER-MANUAL.md", "open-tabs.ps1")
    require_contains("USER-MANUAL.md", "agent_preflight.state")
    require_contains("USER-MANUAL.md", "spawn-refused")
    require_contains("USER-MANUAL.md", "API Error: 403")
    require_contains("USER-MANUAL.md", "taskboard-subagent-fallback")
    require_contains("USER-MANUAL.md", "taskboard-subagent-fallback-packet")
    require_contains("USER-MANUAL.md", "taskboard-subagent-backend")
    require_contains("USER-MANUAL.md", "subagent-fallback.json")
    require_contains("USER-MANUAL.md", "subagent_prompts")
    require_contains("USER-MANUAL.md", "subagent_fallback_available")
    require_contains("USER-MANUAL.md", "subagent_fallback_packet_available")
    require_contains("USER-MANUAL.md", "subagent_fallback_packet_file")
    require_contains("USER-MANUAL.md", "subagent_prompt_roles")
    require_contains("USER-MANUAL.md", "subagent_control_state")
    require_contains("USER-MANUAL.md", "--native-spawn-receipt-json")
    require_contains("USER-MANUAL.md", "--native-result-receipt-json")
    require_contains("USER-MANUAL.md", "subagent_plan_command")
    require_contains("USER-MANUAL.md", "subagent_next_command")
    require_contains("USER-MANUAL.md", "--require-result-evidence")
    require_contains("USER-MANUAL.md", "result_receipt")
    require_contains("USER-MANUAL.md", "superpowers:brainstorming")
    require_contains("USER-MANUAL.md", "superpowers:requesting-code-review")
    require_contains("USER-MANUAL.md", "Codex native subagents")
    require_contains("USER-MANUAL.md", "T0 input boundary")
    require_contains("USER-MANUAL.md", "taskboard-t0-goal-intake")
    require_contains("USER-MANUAL.md", "forbidden fields")
    require_contains("USER-MANUAL.md", "forbidden seed patterns")
    require_contains("USER-MANUAL.md", "REQ skeletons")
    require_contains("USER-MANUAL.md", "MAP risk sections")
    require_contains("USER-MANUAL.md", "requirements、architecture、interface specs")
    require_contains("USER-MANUAL.md", "Startup skill gate")
    require_contains("USER-MANUAL.md", "Evidence enforcement gate")
    require_contains("USER-MANUAL.md", "Idle recheck contract")
    require_contains("USER-MANUAL.md", "action=idle-recheck")
    require_contains("USER-MANUAL.md", "Cross-day cold resume")
    require_contains("USER-MANUAL.md", "cold start is the default correctness path")
    require_contains("USER-MANUAL.md", "claude --resume")
    require_contains("USER-MANUAL.md", "same role, same TASK, and same TASK version")
    require_contains("USER-MANUAL.md", "Current Instruction")
    require_contains("USER-MANUAL.md", "External tool contract")
    require_contains("USER-MANUAL.md", "GitHub tooling")
    require_contains("USER-MANUAL.md", "Chrome/Browser tooling")
    require_contains("USER-MANUAL.md", "Computer Use")
    require_contains("USER-MANUAL.md", "--agent-preflight-command")
    require_contains("USER-MANUAL.md", "--no-agent-preflight")
    require_contains("USER-MANUAL.md", "agent preflight command failed")
    require_contains("references/role-t0.md", "Worker loop contract")
    require_contains("references/role-t0.md", "taskboard.py --root . cycle T{N} --sleep-seconds 120")
    require_contains("references/role-t0.md", "Cross-day cold resume")
    require_contains("references/role-t0.md", "cold start is the default correctness path")
    require_contains("references/role-t0.md", "same role, same TASK, and same TASK version")
    require_contains("references/taskboard-template.md", "taskboard.py --root . cycle T2 --sleep-seconds 120")
    require_contains("references/taskboard-template.md", "Cross-day cold resume")
    require_contains("references/taskboard-template.md", "taskboard_cold_resume_smoke.py")
    require_contains("references/taskboard-template.md", "taskboard_cold_resume_acceptance.py")
    require_contains("references/taskboard-template.md", "taskboard_overnight_field_run.py --root . start --run-id")
    require_contains("references/taskboard-template.md", "taskboard_overnight_field_run.py --root . status")
    require_contains("references/taskboard-template.md", "The status `next_command` omits `--run-id`")
    require_contains("references/taskboard-template.md", 'status --goal "<user goal>"')
    require_contains("references/taskboard-template.md", "taskboard_framework_readiness.py --root .")
    require_contains("references/taskboard-template.md", "field-verification-required")
    require_contains("tests/pressure/cold-resume.md", "fresh next-day worker terminal")
    require_contains("tests/pressure/cold-resume.md", "must recover the topic from TASKBOARD state")
    require_contains("scripts/taskboard_t0.py", 'python scripts/taskboard_sessions.py --root . probe --stale-seconds 300 --goal "<user goal>"')
    require_contains("scripts/taskboard_t0.py", 'python scripts/taskboard_health.py --root . --stale-minutes 30 --goal "<user goal>"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_health.py"')
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_sessions.py"')
    require_contains("scripts/taskboard_health.py", "T0 manager-only")
    require_contains("scripts/taskboard_health.py", "--goal")
    require_contains("scripts/taskboard_health.py", "explicit-goal-no-active-tasks")
    require_contains("scripts/taskboard_health.py", "stalled_tasks")
    require_contains("scripts/taskboard_health.py", "do not execute the development task in T0")
    require_contains("scripts/taskboard_health.py", "role_liveness_state")
    require_contains("scripts/taskboard_health.py", "recover-worker")
    require_contains("scripts/taskboard_health.py", ".taskboard/alive")
    require_contains("references/role-t0.md", "role_liveness_state=alive")
    require_contains("README.md", "worker loop is alive; reissue target")
    require_contains("README.md", "stalled recovery `role_liveness_state`")
    require_contains("USER-MANUAL.md", "worker loop 仍 alive，应重发 target")
    require_contains("USER-MANUAL.md", "stalled recovery `role_liveness_state`")
    require_contains("SKILL.md", "same Git checkout at the same time")
    require_contains("SKILL.md", "separate `git worktree` checkouts")
    require_contains("SKILL.md", ".taskboard/t0/checkout-owner.json")
    require_contains("SKILL.md", "checkout_owner_state=conflict")
    require_contains("SKILL.md", "ClaudeCode and Codex are editing different files")
    require_contains("SKILL.md", "Cross-day cold resume")
    require_contains("SKILL.md", "cold start is the default correctness path")
    require_contains("SKILL.md", "same role, same TASK, and same TASK version")
    require_contains("references/role-t0.md", "Shared checkout ownership")
    require_contains("references/role-t0.md", "Checkout-owner launch guard")
    require_contains("references/role-t0.md", "checkout_owner_state=conflict")
    require_contains("references/role-t0.md", "Peer top-level orchestrators")
    require_contains("references/role-t3.md", "Do not place parallel write agents in the same Git checkout")
    require_contains("README.md", "only one may own the same Git checkout")
    require_contains("README.md", "--checkout-owner-id")
    require_contains("README.md", "checkout_owner_state=conflict")
    require_contains("USER-MANUAL.md", "同一个 Git checkout")
    require_contains("USER-MANUAL.md", ".taskboard/t0/checkout-owner.json")
    require_contains("USER-MANUAL.md", "--checkout-owner-lease-seconds")
    require_contains("USER-MANUAL.md", "git worktree")
    require_contains("references/taskboard-template.md", ".taskboard/t0/checkout-owner.json")
    require_contains("references/taskboard-template.md", "checkout-owner conflicts")
    require_contains("scripts/taskboard_loop.py", "default_checkout_owner_file")
    require_contains("scripts/taskboard_loop.py", "acquire_checkout_owner")
    require_contains("scripts/taskboard_loop.py", "--checkout-owner-id")
    require_contains("scripts/taskboard_progress.py", "checkout_owner_state")
    require_contains("tests/test_taskboard_loop.py", "test_execute_launches_stops_when_checkout_is_owned_by_peer_agent")
    require_contains("tests/test_taskboard_progress.py", "test_progress_surfaces_checkout_owner_conflict")
    require_contains("tests/pressure/README.md", "shared-checkout-collision.md")
    require_contains("tests/pressure/shared-checkout-collision.md", "checkout ownership conflict")
    require_contains("tests/pressure/shared-checkout-collision.md", "RED EVIDENCE")
    require_contains("PROPOSAL-v5-architecture.md", "windows-managed-session-launch-troubleshooting.md")
    require_contains("windows-managed-session-launch-troubleshooting.md", "TASKBOARD 多终端启动排查")
    require_contains("windows-managed-session-launch-troubleshooting.md", "API Error: 403 Request not allowed")
    require_contains("windows-managed-session-launch-troubleshooting.md", "PowerShell 5.1")
    require_contains("windows-managed-session-launch-troubleshooting.md", "open-tabs.ps1")
    require_contains("scripts/taskboard_sessions.py", "heartbeat")
    require_contains("scripts/taskboard_sessions.py", "ALIVE_DIR")
    require_contains("scripts/taskboard_sessions.py", ".taskboard/alive")
    require_contains("scripts/taskboard_sessions.py", "--assignment-id")
    require_contains("scripts/taskboard_sessions.py", "--target-dir")
    require_contains("scripts/taskboard_sessions.py", "{target_file}")
    require_contains("scripts/taskboard_sessions.py", "default_target_dir")
    require_contains("scripts/taskboard_sessions.py", "stale_roles")
    require_contains("scripts/taskboard_sessions.py", "do not execute development")
    require_contains("scripts/package.sh", 'cp "$ROOT_DIR/scripts/taskboard_next.py"')
    require_contains("scripts/taskboard_next.py", 'ROLE_PRIORITY = {')
    require_contains("scripts/taskboard_next.py", '"T0":')


def main() -> int:
    try:
        verify_t0_contract()
    except AssertionError as exc:
        print(f"T0 contract verification failed: {exc}", file=sys.stderr)
        return 1

    print("T0 contract verification passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
